---
# The most valuable linters; they are required to pass for PR to be merged.

linters:
  disable-all: true
  enable:
    - goimports
    - ineffassign
    - govet
    - staticcheck

issues:
  exclude-use-default: false
